### ISSUE TITLE
How to run this program?

### ISSUE THREAD

**Issue by yurkkon** [Sifaldin/To-Do-List#5]
I'm getting those errors.
![image](https://user-images.githubusercontent.com/103900885/180448476-932c4b47-0c7e-4a18-b5a1-dfafaa8324ef.png)

**Comment by 9xcode** [comment]
bro use gradle build 

open directory of this project 
then type "`gradle build`"
 
after successfully build type "`java -classpath build\lib\*;. IP.TodoListApplication.Main`" 

then your code is executing.
